In [172]:
import numpy as np
import pandas as pd
import json
from bs4 import BeautifulSoup
import requests
import xml.etree.ElementTree as ET
from pathlib import Path
from collections import defaultdict

In [173]:
RAW_DIR = Path('data/raw')

## Достаем данные из CSV

In [174]:
df_csv = pd.read_csv(RAW_DIR / 'items.csv', encoding='utf-8', sep=';')
df_csv.head()

,id,name,category,value,updated_at,active
0,1001.0,Механическая клавиатура,Электроника,2999.90,2026-01-10T09:15:00,true
1,1002.0,Беспроводная мышь,электроника,"1599,50",2026-01-11,1
2,1003.0,Монитор 24 дюйма,ЭЛЕКТРОНИКА,18490,11.01.2026 14:30,TRUE
3,1004.0,Кофейная кружка,Дом,450.00,2026/01/12,да
4,1005.0,Настольная лампа,дом,1200,2026-01-13T18:00:00Z,false

## Достаем данные из JSON

In [175]:
with open (RAW_DIR / 'items.json', encoding='utf-8') as file:
    json_data = json.load(file)

df_json = pd.DataFrame(json_data['items'])
df_json.head()

,id,name,category,value,updated_at,active
0,1001,Механическая клавиатура,Электроника,2999.90,2026-01-10T09:15:00,true
1,1002,Беспроводная мышь,электроника,"1599,50",2026-01-11,1
2,1003,Монитор 24 дюйма,ЭЛЕКТРОНИКА,18490,11.01.2026 14:30,TRUE
3,1004,Кофейная кружка,Дом,450.00,2026/01/12,да
4,1005,Настольная лампа,дом,1200,2026-01-13T18:00:00Z,false

## Достаем данные из XML

In [176]:
with open (RAW_DIR / 'items.xml', encoding='utf-8') as file:
    xml_data = ET.parse(file)
root = xml_data.getroot()

items = root.findall('item')
print(f'Длина xml файла: {len(items)}')

all_data = []

for item in items:
    data = {}

    for field in item:
        data[field.tag] = field.text

    all_data.append(data)

print(f'Пример собранных данных из xml:\n {all_data[:1]}')

df_xml = pd.DataFrame(all_data)
print(df_xml.columns.to_list())
print(df_xml.dtypes)
print(df_xml.shape)
df_xml.head()

Длина xml файла: 25
Пример собранных данных из xml:
 [{'id': '1001', 'name': 'Механическая клавиатура', 'category': 'Электроника', 'value': '2999.90', 'updated_at': '2026-01-10T09:15:00', 'active': 'true'}]
['id', 'name', 'category', 'value', 'updated_at', 'active']
id            object
name          object
category      object
value         object
updated_at    object
active        object
dtype: object
(25, 6)

,id,name,category,value,updated_at,active
0,1001,Механическая клавиатура,Электроника,2999.90,2026-01-10T09:15:00,true
1,1002,Беспроводная мышь,электроника,"1599,50",2026-01-11,1
2,1003,Монитор 24 дюйма,ЭЛЕКТРОНИКА,18490,11.01.2026 14:30,TRUE
3,1004,Кофейная кружка,Дом,450.00,2026/01/12,да
4,1005,Настольная лампа,дом,1200,2026-01-13T18:00:00Z,false

```Для каждого источника выведите:
    количество записей;
    список столбцов;
    типы данных;
    количество пропущенных значений;
    количество повторяющихся id.

## CSV

In [177]:
print(f'Количество записей csv-файла: {df_csv.shape[0]}')
print(f'Список столбцов данных: {df_csv.columns.tolist()}')
print(f'типы данных csv-файла:\n{df_csv.dtypes}')
print(f'Количество пропущенных данных:\n{df_csv.isnull().sum()}\n')
print(f'Количество повторяющихся id:\n{df_csv.loc[:, "id"].duplicated().sum()}\n')

Количество записей csv-файла: 25
Список столбцов данных: ['id', 'name', 'category', 'value', 'updated_at', 'active']
типы данных csv-файла:
id            float64
name           object
category       object
value          object
updated_at     object
active         object
dtype: object
Количество пропущенных данных:
id            1
name          0
category      0
value         1
updated_at    1
active        0
dtype: int64

Количество повторяющихся id:
1

## JSON

In [178]:
print(f'Количество записей json-файла: {df_json.shape[0]}')
print(f'Список столбцов данных: {df_json.columns.tolist()}')
print(f'типы данных json-файла:\n{df_json.dtypes}')
print(f'Количество пропущенных данных:\n{df_json.isnull().sum()}\n')
print(f'Количество повторяющихся id:\n{df_json.loc[:, "id"].duplicated().sum()}\n')

Количество записей json-файла: 25
Список столбцов данных: ['id', 'name', 'category', 'value', 'updated_at', 'active']
типы данных json-файла:
id            object
name          object
category      object
value         object
updated_at    object
active        object
dtype: object
Количество пропущенных данных:
id            0
name          0
category      0
value         0
updated_at    0
active        0
dtype: int64

Количество повторяющихся id:
1

## XML

In [179]:
print(f'Количество записей xml-файла: {df_xml.shape[0]}')
print(f'Список столбцов данных: {df_xml.columns.tolist()}')
print(f'типы данных xml-файла:\n{df_xml.dtypes}')
print(f'Количество пропущенных данных:\n{df_xml.isnull().sum()}\n')
print(f'Количество повторяющихся id:\n{df_xml.loc[:, "id"].duplicated().sum()}\n')

Количество записей xml-файла: 25
Список столбцов данных: ['id', 'name', 'category', 'value', 'updated_at', 'active']
типы данных xml-файла:
id            object
name          object
category      object
value         object
updated_at    object
active        object
dtype: object
Количество пропущенных данных:
id            1
name          0
category      0
value         1
updated_at    1
active        0
dtype: int64

Количество повторяющихся id:
1

In [180]:
df = pd.DataFrame(np.vstack([df_csv, df_json, df_xml]), 
                  columns=df_csv.columns.tolist())
df.head()

,id,name,category,value,updated_at,active
0,1001.0,Механическая клавиатура,Электроника,2999.90,2026-01-10T09:15:00,true
1,1002.0,Беспроводная мышь,электроника,"1599,50",2026-01-11,1
2,1003.0,Монитор 24 дюйма,ЭЛЕКТРОНИКА,18490,11.01.2026 14:30,TRUE
3,1004.0,Кофейная кружка,Дом,450.00,2026/01/12,да
4,1005.0,Настольная лампа,дом,1200,2026-01-13T18:00:00Z,false

In [181]:
print(f'{df.shape}\n{df.dtypes}')

(75, 6)
id            object
name          object
category      object
value         object
updated_at    object
active        object
dtype: object

In [182]:
df.loc[:, 'name'].str.strip().str.capitalize().str.replace('  ', ' ')

0     Механическая клавиатура
1           Беспроводная мышь
2            Монитор 24 дюйма
3             Кофейная кружка
4            Настольная лампа
               ...
70        Увлажнитель воздуха
71                 Веб-камера
72           Настольная лампа
73            Коврик для мыши
74      Карандаш механический
Name: name, Length: 75, dtype: object

In [183]:
df.loc[:, 'active'].unique()

array(['true', '1', 'TRUE', 'да', 'false', '0', 'yes', 'no', 'FALSE',
       'нет', 'False'], dtype=object)

In [184]:
def parse_updated_at(value):
    '''Так как параметр format="mixed" в pd.to_datetime 
    не справился с распознаванием форматов из файла, пришлось
    реализовывать эту функцию, которая получает на вход строку
    имитирующую дату или таймстамп, проверяет, является ли она null
    или пустой строкой, после чего проверяет, считался ли корректно
    тип данных datetime, тогда сразу преобразовываем в timestamp,
    в ином случае переходим к анализу строки, прогоняем по всем воз-
    можным форматам и преобразовываем строку в timestamp'''
    from datetime import date, datetime
    
    if pd.isna(value) or str(value).strip() == "":
        return pd.NaT

    if isinstance(value, (date, datetime, pd.Timestamp)):
        timestamp = pd.Timestamp(value)

        if timestamp.tzinfo is not None:
            return (
                timestamp
                .tz_convert("Europe/Moscow")
                .tz_localize(None)
            )

        return timestamp

    value = str(value).strip()

    formats = [
        "%Y-%m-%dT%H:%M:%S%z",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S",
        "%d.%m.%Y %H:%M:%S",
        "%d.%m.%Y %H:%M",
        "%Y-%m-%d",
        "%d.%m.%Y",
        "%Y/%m/%d",
        "%Y.%m.%d",
        "%d/%m/%Y",
    ]

    for date_format in formats:
        try:
            timestamp = pd.to_datetime(value, format=date_format)

            if timestamp.tzinfo is not None:
                timestamp = (
                    timestamp
                    .tz_convert("Europe/Moscow")
                    .tz_localize(None)
                )

            return timestamp

        except (ValueError, TypeError):
            continue

    return pd.NaT

def normalize(df: pd.DataFrame) -> pd.DataFrame:

    df['id'] = pd.to_numeric(
        df['id'], 
        errors='coerce').astype('Int64')
    
    df['name'] = (
        df['name'].astype('string')
        .str.strip().str.replace(r'\s+', ' ', regex=True)
    )

    df['category'] = (
        df['category'].astype('string')
        .str.strip().str.replace(r'\s+', ' ', regex=True)
        .str.capitalize()
    )

    df['value'] = pd.to_numeric(
        df['value'].astype('string')
        .str.strip().str.replace(r'\s+', ' ', regex=True)
        .str.replace(',', '.', regex=False),
        errors='coerce'
    )

    df['updated_at'] = pd.to_datetime(
        df['updated_at'].apply(parse_updated_at),
        format='%m-%d-%Y %H:%M:%S',
        errors='coerce'
    )

    bools = {
        'True': True,
        'Да': True,
        '1': True,
        'Yes': True,
        'False': False,
        'Нет': False,
        '0': False,
        'No': False
    }

    df['active'] = (
        df['active'].astype('string')
        .str.strip().str.capitalize()
    ).map(bools).astype('boolean')

    df = df.drop_duplicates()

    return df

In [185]:
df_cleaned = normalize(df)
df_cleaned.head()

,id,name,category,value,updated_at,active
0,1001,Механическая клавиатура,Электроника,2999.9,2026-01-10 09:15:00,True
1,1002,Беспроводная мышь,Электроника,1599.5,2026-01-11 00:00:00,True
2,1003,Монитор 24 дюйма,Электроника,18490.0,2026-01-11 14:30:00,True
3,1004,Кофейная кружка,Дом,450.0,2026-01-12 00:00:00,True
4,1005,Настольная лампа,Дом,1200.0,2026-01-13 21:00:00,False

In [186]:
print(f'{df_cleaned.shape}\n{df_cleaned.dtypes}')

(24, 6)
id                     Int64
name                  string
category              string
value                float64
updated_at    datetime64[ns]
active               boolean
dtype: object

In [187]:
df_cleaned.to_csv('./data/processed/items_normalized.csv',
                  encoding='utf-8', sep=';', index=False)
df_cleaned.iloc[:, 1:].to_json('./data/processed/items_normalized.json')
df_cleaned.to_xml('./data/processed/items_normalized.xml',
                  encoding='utf-8', index=False)